let name="Animesh Ghoroi";
let schoolName="Masai School";
let grade="A";
let section="c";
let rollNo="0041";
let javascript=75;
let DSA=88;
let cc=75;
console.log("************************************************");
console.log("                  Report Card                   ");
console.log("************************************************");
console.log("Student Name: ",name);
console.log("School Name: ",schoolName);
console.log("Grade: ",grade);
console.log("section: ",section);
console.log("Roll No: ",rollNo);
console.log("Javascript: ",javascript);
console.log("DSA: ",DSA);
console.log("CC: ",cc);